In [24]:
%matplotlib inline
import numpy as np
import pandas as pd
from sklearn.utils import resample
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn import model_selection
from sklearn import metrics
from sklearn.metrics import recall_score
from scipy.stats import zscore
import matplotlib.pyplot as plt 

In [2]:
colnames = ['preg', 'glu', 'bp', 'sft', 'ins', 'bmi', 'dpf', 'age', 'outcome']
df=pd.read_csv("pima-indians-diabetes.data",names=colnames)

In [3]:
df.shape

(768, 9)

In [4]:
X=df.drop(['outcome'],axis=1)
Y=df['outcome']
xtrain,xtest,ytrain,ytest=train_test_split(X,Y,test_size=0.3,random_state=2)

In [5]:
LR=LogisticRegression()
NB=GaussianNB()
KNN=KNeighborsClassifier()

In [6]:
from sklearn.model_selection import GridSearchCV

In [7]:
#UNIFORM => UN WEIGHT
#DISTANCE=> WEIGHTED

In [8]:
knn_G=KNeighborsClassifier()
params={'n_neighbors':np.arange(1,50),'weights':['uniform','distance']}
GS=GridSearchCV(knn_G,params,cv=5,scoring='recall')
GS.fit(X,Y)

C:\Users\Gowtham\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform'),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]), 'weights': ['uniform', 'distance']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='recall', verbose=0)

In [9]:
GS.best_params_

{'n_neighbors': 12, 'weights': 'distance'}

In [10]:
RF=RandomForestClassifier(random_state=0)
param={'n_estimators':np.arange(1,100),'criterion':['entropy','gini']}
GS=GridSearchCV(RF,param,cv=5,scoring='recall')
GS.fit(X,Y)

C:\Users\Gowtham\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators='warn', n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'n_estimators': array([ 1,  2, ..., 98, 99]), 'criterion': ['entropy', 'gini']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='recall', verbose=0)

In [11]:
GS.best_params_

{'criterion': 'entropy', 'n_estimators': 43}

In [97]:
LR=LogisticRegression()
NB=GaussianNB()
KNN=KNeighborsClassifier(n_neighbors=12,weights='distance')
RF=RandomForestClassifier(n_estimators=43,criterion='entropy',random_state=0)

In [13]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=0)

In [14]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [15]:
KNN.fit(x_train,y_train)
y_pred_knn=KNN.predict(x_test)
acc=accuracy_score(y_test,y_pred_knn)*100
cm=confusion_matrix(y_test,y_pred_knn)

In [16]:
print(acc)
print(cm)

75.32467532467533
[[135  22]
 [ 35  39]]


## AFTER SCALLING 

In [17]:
SC=StandardScaler()
XSC=SC.fit_transform(X)

C:\Users\Gowtham\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Gowtham\Anaconda3\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [18]:
knn_G=KNeighborsClassifier()
params={'n_neighbors':np.arange(1,50),'weights':['uniform','distance']}
GS=GridSearchCV(knn_G,params,cv=5,scoring='recall')
GS.fit(XSC,Y)

GS.best_params_

C:\Users\Gowtham\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


{'n_neighbors': 3, 'weights': 'uniform'}

### Applying the best parameters to the algarithms and comaparing

In [19]:
x_train,x_test,y_train,y_test=train_test_split(XSC,Y,test_size=0.3,random_state=0)
KNN=KNeighborsClassifier(n_neighbors=3,weights='uniform')
KNN.fit(x_train,y_train)
y_pred_knn=KNN.predict(x_test)
acc=accuracy_score(y_test,y_pred_knn)*100
cm=confusion_matrix(y_test,y_pred_knn)

print(acc)
print(cm)

72.72727272727273
[[131  26]
 [ 37  37]]


In [25]:
x_train,x_test,y_train,y_test=train_test_split(XSC,Y,test_size=0.3,random_state=0)
KNN=KNeighborsClassifier(n_neighbors=1,weights='uniform')
KNN.fit(x_train,y_train)
y_pred_knn=KNN.predict(x_test)
acc=accuracy_score(y_test,y_pred_knn)*100
cm=confusion_matrix(y_test,y_pred_knn)


print(cm)

[[130  27]
 [ 38  36]]


In [26]:
x_train,x_test,y_train,y_test=train_test_split(XSC,Y,test_size=0.3,random_state=0)
KNN=KNeighborsClassifier(n_neighbors=5,weights='uniform')
KNN.fit(x_train,y_train)
y_pred_knn=KNN.predict(x_test)
acc=accuracy_score(y_test,y_pred_knn)*100
cm=confusion_matrix(y_test,y_pred_knn)

print(acc)
print(cm)

77.05627705627705
[[134  23]
 [ 30  44]]


In [27]:
x_train,x_test,y_train,y_test=train_test_split(XSC,Y,test_size=0.3,random_state=0)
KNN=KNeighborsClassifier(n_neighbors=12,weights='distance')
KNN.fit(x_train,y_train)
y_pred_knn=KNN.predict(x_test)
acc=accuracy_score(y_test,y_pred_knn)*100
cm=confusion_matrix(y_test,y_pred_knn)
rs=recall_score(y_test,y_pred_knn)*100
print(acc)
print(cm)
print(rs)

77.05627705627705
[[137  20]
 [ 33  41]]
55.4054054054054


In [28]:
from sklearn.metrics import recall_score

In [45]:
rs_12_weighted=[]
for i in range(0,3):
    x_train,x_test,y_train,y_test=train_test_split(XSC,Y,test_size=0.3,random_state=i)
    KNN=KNeighborsClassifier(n_neighbors=12,weights='distance')
    KNN.fit(x_train,y_train)
    y_pred_knn=KNN.predict(x_test)
    acc=accuracy_score(y_test,y_pred_knn)*100
    cm=confusion_matrix(y_test,y_pred_knn)
    rs=recall_score(y_test,y_pred_knn)*100
    rs_12_weighted.append(rs)
#    print(acc)
 #   print(cm)
print(rs_12_weighted)
    

[55.4054054054054, 57.647058823529406, 42.10526315789473]


In [31]:
rs_3_uniform=[]
for i in range(0,3):
    x_train,x_test,y_train,y_test=train_test_split(XSC,Y,test_size=0.3,random_state=i)
    KNN=KNeighborsClassifier(n_neighbors=3,weights='uniform')
    KNN.fit(x_train,y_train)
    y_pred_knn=KNN.predict(x_test)
    acc=accuracy_score(y_test,y_pred_knn)*100
    cm=confusion_matrix(y_test,y_pred_knn)
    rs=recall_score(y_test,y_pred_knn)*100
    rs_3_uniform.append(rs)
#    print(acc)
 #   print(cm)
print(rs_3_uniform)
    

[50.0, 52.94117647058824, 51.31578947368421]


In [32]:
rs_5_uniform=[]
for i in range(0,3):
    x_train,x_test,y_train,y_test=train_test_split(XSC,Y,test_size=0.3,random_state=i)
    KNN=KNeighborsClassifier(n_neighbors=5,weights='uniform')
    KNN.fit(x_train,y_train)
    y_pred_knn=KNN.predict(x_test)
    acc=accuracy_score(y_test,y_pred_knn)*100
    cm=confusion_matrix(y_test,y_pred_knn)
    rs=recall_score(y_test,y_pred_knn)*100
    rs_5_uniform.append(rs)
#    print(acc)
 #   print(cm)

    

In [37]:
rs_7_uniform=[]
for i in range(0,3):
    x_train,x_test,y_train,y_test=train_test_split(XSC,Y,test_size=0.3,random_state=i)
    KNN=KNeighborsClassifier(n_neighbors=7,weights='uniform')
    KNN.fit(x_train,y_train)
    y_pred_knn=KNN.predict(x_test)
    acc=accuracy_score(y_test,y_pred_knn)*100
    cm=confusion_matrix(y_test,y_pred_knn)
    rs=recall_score(y_test,y_pred_knn)*100
    rs_7_uniform.append(rs)
#    print(acc)
 #   print(cm)
print(rs_7_uniform)
    

[52.702702702702695, 58.82352941176471, 42.10526315789473]


In [40]:
rs_9_uniform=[]
for i in range(0,3):
    x_train,x_test,y_train,y_test=train_test_split(XSC,Y,test_size=0.3,random_state=i)
    KNN=KNeighborsClassifier(n_neighbors=9,weights='uniform')
    KNN.fit(x_train,y_train)
    y_pred_knn=KNN.predict(x_test)
    acc=accuracy_score(y_test,y_pred_knn)*100
    cm=confusion_matrix(y_test,y_pred_knn)
    rs=recall_score(y_test,y_pred_knn)*100
    rs_9_uniform.append(rs)
#    print(acc)
 #   print(cm)
print(rs_9_uniform)
    

[54.054054054054056, 58.82352941176471, 42.10526315789473]


In [42]:
rs_12_uniform=[]
for i in range(0,3):
    x_train,x_test,y_train,y_test=train_test_split(XSC,Y,test_size=0.3,random_state=i)
    KNN=KNeighborsClassifier(n_neighbors=12,weights='uniform')
    KNN.fit(x_train,y_train)
    y_pred_knn=KNN.predict(x_test)
    acc=accuracy_score(y_test,y_pred_knn)*100
    cm=confusion_matrix(y_test,y_pred_knn)
    rs=recall_score(y_test,y_pred_knn)*100
    rs_12_uniform.append(rs)
#    print(acc)
 #   print(cm)
print(rs_12_uniform)
    

[45.94594594594595, 50.588235294117645, 35.526315789473685]


In [53]:
print("n_neigbhors= 3 and uniform")
print("Mean",np.mean(rs_3_uniform),"  and variance",np.var(rs_3_uniform,ddof=1))
print("n_neigbhors= 5 and uniform")
print("Mean",np.mean(rs_5_uniform)," and variance",np.var(rs_5_uniform,ddof=1))
print("n_neigbhors= 7 and uniform")
print("Mean",np.mean(rs_7_uniform),"and variance",np.var(rs_7_uniform,ddof=1))
print("n_neigbhors= 7 and uniform")
print("Mean",np.mean(rs_9_uniform),"and variance",np.var(rs_9_uniform,ddof=1))
print("n_neigbhors= 12 and uniform")
print("Mean",np.mean(rs_12_uniform),"and variance",np.var(rs_12_uniform,ddof=1))
print("n_neigbhors= 12 and weighted")
print(np.mean(rs_12_weighted)," and variance",np.var(rs_12_weighted,ddof=1))
print("n_neigbhors= 12 and weighted")
print(np.mean(rs_12_weighted)," and variance",np.var(rs_12_weighted,ddof=1))

n_neigbhors= 3 and uniform
Mean 51.41898864809082   and variance 2.1706173099841264
n_neigbhors= 5 and uniform
Mean 57.66295707472178  and variance 48.181811288516585
n_neigbhors= 7 and uniform
Mean 51.510798724421015 and variance 55.02216482916057
n_neigbhors= 7 and uniform
Mean 51.66094887457117 and variance 74.1703209338728
n_neigbhors= 12 and uniform
Mean 44.02016567651242 and variance 59.49682702569814
n_neigbhors= 12 and weighted
51.71924246227652  and variance 70.57770106055766


In [62]:
RF=RandomForestClassifier(n_estimators=43,criterion='entropy',random_state=0)
RF_43=[]
for i in range(0,3):
    x_train,x_test,y_train,y_test=train_test_split(XSC,Y,test_size=0.3,random_state=i)
    RF.fit(x_train,y_train)
    y_pred_RF=RF.predict(x_test)
    acc=accuracy_score(y_test,y_pred_RF)*100
    cm=confusion_matrix(y_test,y_pred_RF)
    rs=recall_score(y_test,y_pred_RF)*100
    RF_43.append(rs)
#    print(acc)
 #   print(cm)

print(RF_43)    

[55.4054054054054, 62.35294117647059, 51.31578947368421]


In [63]:
RF=RandomForestClassifier(n_estimators=51,criterion='entropy',random_state=0)
RF_51=[]
for i in range(0,3):
    x_train,x_test,y_train,y_test=train_test_split(XSC,Y,test_size=0.3,random_state=i)
    RF.fit(x_train,y_train)
    y_pred_RF=RF.predict(x_test)
    acc=accuracy_score(y_test,y_pred_RF)*100
    cm=confusion_matrix(y_test,y_pred_RF)
    rs=recall_score(y_test,y_pred_RF)*100
    RF_51.append(rs)
#    print(acc)
 #   print(cm)

print(RF_51)    

[56.75675675675676, 62.35294117647059, 52.63157894736842]


In [64]:
np.var(RF_51)

15.871028400881343

20.756881052170915

In [77]:
RF=RandomForestClassifier(n_estimators=10,criterion='entropy',random_state=0)
RF_10=[]
cm_10=[]
for i in range(0,3):
    x_train,x_test,y_train,y_test=train_test_split(XSC,Y,test_size=0.3,random_state=i)
    RF.fit(x_train,y_train)
    y_pred_RF=RF.predict(x_test)
    acc=accuracy_score(y_test,y_pred_RF)*100
    cm=confusion_matrix(y_test,y_pred_RF)
    rs=recall_score(y_test,y_pred_RF)*100
    RF_10.append(rs)
    cm_10.append(cm)
#   print(acc)
    print(cm)
#print(cm_10)
print(RF_10) 
print(np.var(RF_10))

[[136  21]
 [ 39  35]]
[[133  13]
 [ 46  39]]
[[138  17]
 [ 45  31]]
[47.2972972972973, 45.88235294117647, 40.78947368421053]
7.810139426222435


In [116]:
LR1=LogisticRegression()
NB1=GaussianNB()
KNN1=KNeighborsClassifier(n_neighbors=12,weights='uniform')
RF1=RandomForestClassifier(n_estimators=43,criterion='entropy',random_state=0)

In [117]:
kf=KFold(n_splits=5,shuffle=True,random_state=0)
for model,name in zip([LR1,NB1,RF1,KNN1],['LR','NB','RF','KNN']):
    roc_auc=[]
    for train,test, in kf.split(XSC,Y):
        xtrain,xtest=XSC[train,:],XSC[test,:]
        ytrain,ytest=Y.iloc[train],Y.iloc[test]
        model.fit(xtrain,ytrain)
        y_pred=model.predict(xtest)
        fpr,tpr,_=roc_curve(ytest,y_pred)
        roc_auc.append(auc(fpr,tpr))
    print("AUC SCORE : %0.02F(+/- %0.5F)[%s]"%(np.mean(roc_auc)*100,np.var(roc_auc,ddof=1),name))

C:\Users\Gowtham\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Gowtham\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Gowtham\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Gowtham\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Gowtham\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to

AUC SCORE : 72.92(+/- 0.00054)[LR]
AUC SCORE : 71.27(+/- 0.00237)[NB]
AUC SCORE : 71.67(+/- 0.00219)[RF]
AUC SCORE : 67.67(+/- 0.00119)[KNN]
